[package]
name = "dusk-api"
version = "0.0.2"
authors = ["Andy Gozas <andy@gozas.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
rustc_version = "0.3.0"

[dependencies]
libloading = "*"
